### PR TITLE
add a base opacity setting

### PR DESCRIPTION
**Pull request by mwcz**
Screenshot from 2020-11-25 13-51-51

### CODE REVIEW

**Comment by iphands** [comment]
Why this if the background support alpha?
So you can make the text have opacity too?

**Comment by iphands** [comment]
Care if its a name like `base_opacity`?
Also I think the README.md should say something like:
> Affects `window` and all sub widgets

Thoughts?

**Comment by mwcz** [comment]
> Care if its a name like `base_opacity`?
> Also I think the README.md should say something like:
> 
> > Affects `window` and all sub widgets
> 
> Thoughts?

Sure base opacity sounds great. I'll submit a change when I get a chance, maybe Monday.

**Comment by mwcz** [comment]
@iphands renamed and added the README change :+1:

**Comment by iphands** [comment]
<3 it!

**Pull request merged**
